import { createThemePlugin } from '@vuetify/v0'

export default defineNuxtPlugin(nuxtApp => {
  nuxtApp.vueApp.use(createThemePlugin({
    default: 'light',
    target: 'html',
    themes: {
      light: {
        dark: false,
        colors: {
          'primary': '#3b82f6',
          'secondary': '#64748b',
          'error': '#ef4444',
          'info': '#1867c0',
          'success': '#22c55e',
          'warning': '#f59e0b',
          'background': '#f5f5f5',
          'surface': '#ffffff',
          'surface-tint': '#f5f5f5',
          'surface-variant': '#eeeeee',
          'divider': '#e0e0e0',
          'on-primary': '#ffffff',
          'on-secondary': '#ffffff',
          'on-error': '#ffffff',
          'on-info': '#ffffff',
          'on-success': '#ffffff',
          'on-warning': '#1a1a1a',
          'on-background': '#212121',
          'on-surface': '#212121',
          'on-surface-variant': '#666666',
        },
      },
      dark: {
        dark: true,
        colors: {
          'primary': '#c4b5fd',
          'secondary': '#94a3b8',
          'error': '#f87171',
          'info': '#38bdf8',
          'success': '#4ade80',
          'warning': '#fb923c',
          'background': '#121212',
          'surface': '#1a1a1a',
          'surface-tint': '#2a2a2a',
          'surface-variant': '#1e1e1e',
          'divider': '#404040',
          'on-primary': '#1a1a1a',
          'on-secondary': '#1a1a1a',
          'on-error': '#1a1a1a',
          'on-info': '#1a1a1a',
          'on-success': '#1a1a1a',
          'on-warning': '#1a1a1a',
          'on-background': '#e0e0e0',
          'on-surface': '#e0e0e0',
          'on-surface-variant': '#a0a0a0',
        },
      },
    },
  }))
})
